sudo: false
language: python
python:
  - '3.8'
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run nox -s tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
